server:
  port: 9090
spring:
  thymeleaf:
    cache: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/xiaoshu?characterEnconding=utf-8&serverTimezone=UTC
    username: root
    password:
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.lu.j1993.pojo
